$(document).ready(function(){
	//set up carousel
	$(".mainCarousel").carousel({
      interval: 6000
    });
	
	$(".mainCarousel").carousel("next");
	
	//thumbnail handlers
	$("#item1").click(function(){
		$("#mainCarousel").carousel(0);
	});
	$("#item2").click(function(){
		$("#mainCarousel").carousel(1);
	});
	$("#item3").click(function(){
		$("#mainCarousel").carousel(2);
	});
	$("#item4").click(function(){
		$("#mainCarousel").carousel(3);
	});
	$("#item5").click(function(){
		$("#mainCarousel").carousel(4);
	});
	$("#item6").click(function(){
		$("#mainCarousel").carousel(5);
	});
	$("#item7").click(function(){
		$("#mainCarousel").carousel(6);
	});
	$("#item8").click(function(){
		$("#mainCarousel").carousel(7);
	});
	$("#item9").click(function(){
		$("#mainCarousel").carousel(8);
	});
	$("#item10").click(function(){
		$("#mainCarousel").carousel(9);
	});
	$("#item11").click(function(){
		$("#mainCarousel").carousel(10);
	});
	$("#item12").click(function(){
		$("#mainCarousel").carousel(11);
	});
	$("#item13").click(function(){
		$("#mainCarousel").carousel(12);
	});
	$("#item14").click(function(){
		$("#mainCarousel").carousel(13);
	});
	$("#item15").click(function(){
		$("#mainCarousel").carousel(14);
	});
	$("#item16").click(function(){
		$("#mainCarousel").carousel(15);
	});
	$("#item17").click(function(){
		$("#mainCarousel").carousel(16);
	});
	$("#item18").click(function(){
		$("#mainCarousel").carousel(17);
	});
	$("#item19").click(function(){
		$("#mainCarousel").carousel(18);
	});
	$("#item20").click(function(){
		$("#mainCarousel").carousel(19);
	});
	$("#item21").click(function(){
		$("#mainCarousel").carousel(20);
	});
	$("#item22").click(function(){
		$("#mainCarousel").carousel(21);
	});
	$("#item23").click(function(){
		$("#mainCarousel").carousel(22);
	});
	$("#item24").click(function(){
		$("#mainCarousel").carousel(23);
	});
	$("#item25").click(function(){
		$("#mainCarousel").carousel(24);
	});
	$("#item26").click(function(){
		$("#mainCarousel").carousel(25);
	});
	$("#item27").click(function(){
		$("#mainCarousel").carousel(26);
	});
	$("#item28").click(function(){
		$("#mainCarousel").carousel(27);
	});
	$("#item29").click(function(){
		$("#mainCarousel").carousel(28);
	});
});